############################################
##                  API                   ##
############################################ 
# KMA-weather data.go.kr
kma.api.key=4fcc005235fd105acb8c865f5c33306dcc54732e010efd5b3e274c4ebc65dba4
vworld.api.key=93BA2A89-9B20-3137-9898-4FD1290169AB

# NaverEmail 
naver.host=smtp.naver.com
naver.user=1023jsm@naver.com
naver.password=D2V1TEL12J44

############################################
## MAIL
############################################

spring.mail.host=smtp.naver.com
spring.mail.port=587
spring.mail.username=1023jsm@naver.com
spring.mail.password=D2V1TEL12J44

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com

# ChatGpt

# CoolSMS
#coolsms.apikey= 
#coolsms.apisecret= 


# KakaoPay Api
#kakaopay.secret-key-dev= 
#kakaopay.approval-url=http://localhost:8080/api/pay/success
#kakaopay.fail-url=http://localhost:8080/api/pay/fail
#kakaopay.cancel-url=http://localhost:8080/api/pay/cancel 

 
#naver.ocr.secret=
#naver.ocr.apiUrl=https://naveropenapi.apigw.ntruss.com/ocr/v1/thejoa_ocr

