############################################
##                  API                   ##
############################################ 
# KMA-weather data.go.kr
#kma.api= 

# NaverEmail 
naver.host=smtp.naver.com
naver.user=1023jsm@naver.com
naver.password=D2V1TEL12J44

# ChatGpt
# CoolSMS
#coolsms.apikey= 
#coolsms.apisecret= 


# KakaoPay Api
#kakaopay.secret-key-dev= 
#kakaopay.approval-url=http://localhost:8080/api/pay/success
#kakaopay.fail-url=http://localhost:8080/api/pay/fail
#kakaopay.cancel-url=http://localhost:8080/api/pay/cancel 

 
#naver.ocr.secret=
#naver.ocr.apiUrl=https://naveropenapi.apigw.ntruss.com/ocr/v1/thejoa_ocr

