############################################
##                  API                   ##
############################################ 
# KMA-weather data.go.kr


############################################
## MAIL
############################################


# ChatGpt
openai.api.key=

# CoolSMS
#coolsms.apikey= 
#coolsms.apisecret= 


# KakaoPay Api
#kakaopay.secret-key-dev= 
#kakaopay.approval-url=http://localhost:8080/api/pay/success
#kakaopay.fail-url=http://localhost:8080/api/pay/fail
#kakaopay.cancel-url=http://localhost:8080/api/pay/cancel 

 
#naver.ocr.secret=
#naver.ocr.apiUrl=https://naveropenapi.apigw.ntruss.com/ocr/v1/thejoa_ocr

